import { existsSync } from "node:fs";
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";

const SHIM_MARKER = "Generated by opencode-insights";

export type CliShimOptions = {
  enabled?: boolean | undefined;
  homeDir?: string | undefined;
  packageRoot?: string | undefined;
  platform?: NodeJS.Platform | undefined;
};

export type CliShimResult =
  | { path: string; status: "created" | "updated" | "unchanged" }
  | { path: string; status: "skipped"; reason: string };

export function resolveCliShimPath(options: Pick<CliShimOptions, "homeDir" | "platform"> = {}) {
  const home = options.homeDir ?? homedir();
  const name = options.platform === "win32" ? "opencode-insights.cmd" : "opencode-insights";
  return join(home, ".local", "bin", name);
}

export function createCliShimContent(cliPath: string, platform: NodeJS.Platform = process.platform) {
  if (platform === "win32") {
    return [`@echo off`, `rem ${SHIM_MARKER}. Do not edit.`, `node ${JSON.stringify(cliPath)} %*`, ""].join("\r\n");
  }

  return [`#!/usr/bin/env sh`, `# ${SHIM_MARKER}. Do not edit.`, `exec node ${shellQuote(cliPath)} "$@"`, ""].join("\n");
}

export async function ensureCliShim(options: CliShimOptions = {}): Promise<CliShimResult> {
  const platform = options.platform ?? process.platform;
  const path = resolveCliShimPath({ homeDir: options.homeDir, platform });

  if (options.enabled === false || process.env.OPENCODE_INSIGHTS_CLI_SHIM === "0") {
    return { path, status: "skipped", reason: "disabled" };
  }

  const packageRoot = options.packageRoot ?? defaultPackageRoot();
  const content = createCliShimContent(join(packageRoot, "dist", "cli.js"), platform);

  const existed = existsSync(path);
  if (existed) {
    const existing = await readFile(path, "utf8");
    if (existing === content) return { path, status: "unchanged" };
    if (!existing.includes(SHIM_MARKER)) {
      return { path, status: "skipped", reason: "existing command is not managed by opencode-insights" };
    }
  }

  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
  if (platform !== "win32") await chmod(path, 0o755);
  return { path, status: existed ? "updated" : "created" };
}

function defaultPackageRoot() {
  return dirname(dirname(fileURLToPath(import.meta.url)));
}

function shellQuote(value: string) {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
